### ISSUE TITLE
chainer->ONNX->Mxnet failed due to Input shape vs padding spec mismatch

### ISSUE THREAD

**Issue by mingxiaoh** [chainer/onnx-chainer#14]
hello, 
any suggestion for this error? Thanks in advance.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export.py", line 52, in <module>
    main()
  File "export.py", line 45, in main
    save_as_onnx_then_import_from_mxnet(model, 'vgg16.onnx')
  File "export.py", line 29, in save_as_onnx_then_import_from_mxnet
    label_shapes=None)
  File "/miniconda/lib/python3.6/site-packages/mxnet/module/module.py", line 428, in bind
    state_names=self._state_names)
  File "/miniconda/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 237, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/miniconda/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 333, in bind_exec
    shared_group))
  File "/miniconda/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 611, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/miniconda/lib/python3.6/site-packages/mxnet/symbol/symbol.py", line 1494, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
input_0: (1, 3, 224, 224)
Error in operator pad0: [18:08:15] src/operator/./pad-inl.h:211: Input shape vs padding spec mismatch.

**Comment by mitmul** [comment]
@mingxiaoh Hi, I think it has been already fixed in the latest version of ONNX-Chainer. Please check it out.
