### ISSUE TITLE
quick start example MemoryError

### ISSUE THREAD

**Issue by aaronmarkham** [chainer/onnx-chainer#37]
When I run the [quick start example](https://github.com/chainer/onnx-chainer#quick-start) in the Readme, I get the following error:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    onnx_chainer.export(model, x, filename='vgg16.onnx')
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/site-packages/onnx_chainer/export.py", line 237, in export
    checker.check_graph(onnx_graph)
  File "/home/ubuntu/anaconda3/envs/chainer_p36/lib/python3.6/site-packages/onnx/checker.py", line 46, in checker
    proto.SerializeToString(), ctx)
MemoryError
```
This is happening on a c5d.large instance type on a Deep Learning AMI on AWS. It has 4GB of RAM.

**Comment by mitmul** [comment]
Hm, I guess Protobuf may require larger memory than 4GB when deserializing vgg16.onnx. Could you try the same code on another machine which has larger memory?

**Comment by disktnk** [comment]
We close this issue but feel free to make new issue when having a trouble on exporting.
