### ISSUE TITLE
Cannot fetch intermediate variable

### ISSUE THREAD

**Issue by Hakuyume** [chainer/onnx-chainer#57]
Tested with chainer==5.1.0 and onnx-chainer==1.3.0a1.

```python
import numpy as np

import chainer
import chainer.links as L
import onnx_chainer


class Model(chainer.Chain):

    def __init__(self):
        super().__init__()
        with self.init_scope():
            self.l1 = L.Linear(4)
            self.l2 = L.Linear(5)

    def __call__(self, x):
        y = self.l1(x)
        z = self.l2(y)
        return y, z


model = Model()
x = np.empty((1, 3), dtype=np.float32)
onnx_chainer.export(model, (x,))
```
```
Traceback (most recent call last):
  File "***.py", line 24, in <module>
    onnx_chainer.export(model, (x,))
  File "***/lib/python3.7/site-packages/onnx_chainer/export.py", line 306, in export
    checker.check_model(model)
  File "***/lib/python3.7/site-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Input_0' of node: 
input: "Input_0" input: "139839959553304" input: "139839959553528" output: "Gemm_0" op_type: "Gemm" attribute { name: "alpha" f: 1 type: FLOAT } attribute { name: "beta" f: 1 type: FLOAT } attribute { name: "transA" i: 0 type: INT } attribute { name: "transB" i: 1 type: INT }
 is not output of any previous nodes.
```

Note that all of the following conditions worked well.
- Return `z` only.
```python
    def __call__(self, x):
        y = self.l1(x)
        z = self.l2(y)
        return z
```
- Return `y` only.
```python
    def __call__(self, x):
        y = self.l1(x)
        z = self.l2(y)
        return y
```
- `y` is not intermediate variable.
```python
    def __call__(self, x):
        y = self.l1(x)
        z = self.l2(x)
        return y, z
```

**Comment by mitmul** [comment]
Thanks for reporting this issue. It's a bug.

**Comment by disktnk** [comment]
Currently, the reproduce example occurs not error on exporting, but output graph is appropriate.

![image](https://user-images.githubusercontent.com/414255/53227606-08297200-36c2-11e9-9d8c-03bf1065b570.png)
